title: Peter Wise
baseurl: /
permalink: '/:title/'
color_scheme: light
accent_color: blue
header:
  has_nav: true
  title: Exto
footer:
  content: '&copy; Peter Wise. All rights reserved.'
  has_social: true
  links: []
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
